### PR TITLE
Migrate to github actions for CI

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Use github actions for CI and remove travis CI.

ENDRELEASENOTES

Does github actions have something like coverity scan? I think apart from that this should be pretty much equivalent to what was done before.

### CODE REVIEW

**Comment by rete** [comment]
@andresailer Github actions are not triggered in this PR. I looked in the repository settings and couldn't find where to add github actions to the required statuses to pass for PRs. Any idea?

**Comment by rete** [comment]
@andresailer @tmadlener  No way to trigger github actions. Can it be possible that we have to merge this before it triggers Github actions?

**Comment by tmadlener** [comment]
I am actually not sure. The github actions seem to run succesfully though: https://github.com/tmadlener/SIO/actions/runs/480911173

So at least this shouldn't break anything.

**Comment by andresailer** [comment]
1. action not running: https://github.com/tmadlener/SIO/actions doesn't list anything about the "pull_request" event having triggered anything. So maybe because of that there is no status here. Maybe the close/open triggers the pull request status. On this repo (not Thomas' fork) it will  only run once merged
2. Required: this setting is under branch, but you can only select checks that recently ran
3. coverity: hasn't really worked in some time :( of course the running and pushing should also be possible via github action (maybe there is one somewhere already)

**Comment by rete** [comment]
I suggest we try to merge this and see.
@tmadlener After the merge, wait a bit before rebasing the other PR.

**Review by rete — APPROVED** [review]

**Pull request merged**
